### ISSUE TITLE
Migrate to null safety

### ISSUE THREAD

**Issue by Cynnexis** [Cynnexis/notifiable_iterables#6]
https://medium.com/dartlang/announcing-dart-null-safety-beta-87610fee6730

**Comment by andyduke** [comment]
@Cynnexis When do you plan to publish the null-safety version on pub.dev?

**Comment by Cynnexis** [comment]
The package has been updated for the null-safety migration. You can download the lastest version with:

```yaml
  notifiable_iterables: ^1.1.1
```
